import { Course, CourseSection, Department, DegreeProgram, ChangeRequest } from '../types/course';
import { StudentProfile, StudentEnrollment, DegreeProgress, CompletedCourseRecord } from '../types/student';
import { FacultyProfile, ClassRosterStudent, GradeRecord } from '../types/faculty';
import { NotificationItem } from '../types/notification';
import { EnrollmentTrendItem, DepartmentDistributionItem, CoursePopularityItem, FacultyWorkloadItem } from '../types/report';

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 1, code: 'CS', name: 'Computer Science & Engineering' },
  { id: 2, code: 'MATH', name: 'Mathematics & Statistics' },
  { id: 3, code: 'PHYS', name: 'Physics & Applied Sciences' },
  { id: 4, code: 'BUS', name: 'Business Administration' },
  { id: 5, code: 'ENG', name: 'Electrical Engineering' },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 1,
    courseCode: 'CS-101',
    courseNumber: 101,
    title: 'Introduction to Computer Science & Programming',
    description: 'Fundamental concepts of computer science, algorithms, basic data structures, and Python programming.',
    credits: 3,
    capacity: 45,
    enrolledCount: 42,
    departmentId: 1,
    departmentName: 'Computer Science & Engineering',
    level: 'UNDERGRADUATE',
    status: 'ACTIVE',
  },
  {
    id: 2,
    courseCode: 'CS-301',
    courseNumber: 301,
    title: 'Data Structures and Algorithms',
    description: 'Trees, graphs, dynamic programming, space-time complexity analysis, and modern algorithms.',
    credits: 4,
    capacity: 35,
    enrolledCount: 35,
    departmentId: 1,
    departmentName: 'Computer Science & Engineering',
    level: 'UNDERGRADUATE',
    status: 'ACTIVE',
  },
  {
    id: 3,
    courseCode: 'CS-501',
    courseNumber: 501,
    title: 'Advanced Software Engineering & Architecture',
    description: 'Microservices architecture, REST APIs, design patterns, scalable cloud deployment, and devops.',
    credits: 3,
    capacity: 30,
    enrolledCount: 22,
    departmentId: 1,
    departmentName: 'Computer Science & Engineering',
    level: 'GRADUATE',
    status: 'ACTIVE',
  },
  {
    id: 4,
    courseCode: 'MATH-201',
    courseNumber: 201,
    title: 'Linear Algebra & Differential Equations',
    description: 'Vector spaces, matrices, eigenvalues, linear systems, and differential applications.',
    credits: 4,
    capacity: 40,
    enrolledCount: 38,
    departmentId: 2,
    departmentName: 'Mathematics & Statistics',
    level: 'UNDERGRADUATE',
    status: 'ACTIVE',
  },
  {
    id: 5,
    courseCode: 'BUS-402',
    courseNumber: 402,
    title: 'Corporate Strategy & Leadership',
    description: 'Strategic management, organizational leadership, financial metrics, and executive case studies.',
    credits: 3,
    capacity: 30,
    enrolledCount: 28,
    departmentId: 4,
    departmentName: 'Business Administration',
    level: 'UNDERGRADUATE',
    status: 'ACTIVE',
  },
  {
    id: 6,
    courseCode: 'ENG-220',
    courseNumber: 220,
    title: 'Digital Systems & Logic Design',
    description: 'Boolean algebra, logic gates, combinational and sequential circuit design, and VHDL hardware modeling.',
    credits: 4,
    capacity: 25,
    enrolledCount: 24,
    departmentId: 5,
    departmentName: 'Electrical Engineering',
    level: 'UNDERGRADUATE',
    status: 'ACTIVE',
  }
];

export const MOCK_SECTIONS: CourseSection[] = [
  {
    id: 1,
    courseId: 1,
    courseCode: 'CS-101',
    courseTitle: 'Introduction to Computer Science',
    sectionNumber: 'SEC-01',
    instructorName: 'Prof. Alice Smith',
    semester: 'FALL',
    year: 2025,
    scheduleDays: 'Mon, Wed',
    scheduleTime: '09:00 AM - 10:30 AM',
    location: 'Turing Hall 101',
    capacity: 45,
    enrolledCount: 42,
    waitlistCount: 2,
  },
  {
    id: 2,
    courseId: 2,
    courseCode: 'CS-301',
    courseTitle: 'Data Structures and Algorithms',
    sectionNumber: 'SEC-01',
    instructorName: 'Prof. Alice Smith',
    semester: 'FALL',
    year: 2025,
    scheduleDays: 'Tue, Thu',
    scheduleTime: '11:00 AM - 12:30 PM',
    location: 'Lovelace Lab 302',
    capacity: 35,
    enrolledCount: 35,
    waitlistCount: 5,
  },
  {
    id: 3,
    courseId: 3,
    courseCode: 'CS-501',
    courseTitle: 'Advanced Software Engineering',
    sectionNumber: 'SEC-01',
    instructorName: 'Prof. Robert Taylor',
    semester: 'FALL',
    year: 2025,
    scheduleDays: 'Mon, Wed',
    scheduleTime: '02:00 PM - 03:30 PM',
    location: 'Hopper Auditorium 205',
    capacity: 30,
    enrolledCount: 22,
    waitlistCount: 0,
  },
  {
    id: 4,
    courseId: 4,
    courseCode: 'MATH-201',
    courseTitle: 'Linear Algebra',
    sectionNumber: 'SEC-02',
    instructorName: 'Prof. Elena Rostova',
    semester: 'FALL',
    year: 2025,
    scheduleDays: 'Fri',
    scheduleTime: '09:00 AM - 12:00 PM',
    location: 'Euler Hall 401',
    capacity: 40,
    enrolledCount: 38,
    waitlistCount: 1,
  }
];

export const MOCK_STUDENT_PROFILE: StudentProfile = {
  id: 1,
  userId: 1,
  studentIdNumber: 'NEX-2024-8842',
  firstName: 'John',
  lastName: 'Doe',
  email: 'john.doe@nexus.edu',
  phoneNumber: '+1 (555) 234-5678',
  major: 'Computer Science',
  enrollmentYear: 2024,
  academicStanding: 'GOOD_STANDING',
  gpa: 3.82,
};

export const MOCK_ALL_STUDENTS: StudentProfile[] = [
  MOCK_STUDENT_PROFILE,
  {
    id: 2,
    userId: 5,
    studentIdNumber: 'NEX-2024-7711',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    email: 'sarah.j@nexus.edu',
    major: 'Electrical Engineering',
    enrollmentYear: 2024,
    academicStanding: 'GOOD_STANDING',
    gpa: 3.65,
  },
  {
    id: 3,
    userId: 6,
    studentIdNumber: 'NEX-2023-9090',
    firstName: 'Marcus',
    lastName: 'Vance',
    email: 'marcus.vance@nexus.edu',
    major: 'Mathematics',
    enrollmentYear: 2023,
    academicStanding: 'DEANS_LIST',
    gpa: 3.95,
  },
  {
    id: 4,
    userId: 7,
    studentIdNumber: 'NEX-2025-1102',
    firstName: 'Emily',
    lastName: 'Watson',
    email: 'emily.w@nexus.edu',
    major: 'Computer Science',
    enrollmentYear: 2025,
    academicStanding: 'GOOD_STANDING',
    gpa: 3.88,
  },
  {
    id: 5,
    userId: 8,
    studentIdNumber: 'NEX-2024-5541',
    firstName: 'David',
    lastName: 'Miller',
    email: 'david.m@nexus.edu',
    major: 'Business Administration',
    enrollmentYear: 2024,
    academicStanding: 'GOOD_STANDING',
    gpa: 3.52,
  }
];

export const MOCK_STUDENT_ENROLLMENTS: StudentEnrollment[] = [
  {
    id: 101,
    studentId: 1,
    sectionId: 1,
    courseCode: 'CS-101',
    courseTitle: 'Introduction to Computer Science',
    credits: 3,
    instructorName: 'Prof. Alice Smith',
    scheduleDays: 'Mon, Wed',
    scheduleTime: '09:00 AM - 10:30 AM',
    location: 'Turing Hall 101',
    status: 'ENROLLED',
    enrolledAt: '2025-08-15',
  },
  {
    id: 102,
    studentId: 1,
    sectionId: 2,
    courseCode: 'CS-301',
    courseTitle: 'Data Structures and Algorithms',
    credits: 4,
    instructorName: 'Prof. Alice Smith',
    scheduleDays: 'Tue, Thu',
    scheduleTime: '11:00 AM - 12:30 PM',
    location: 'Lovelace Lab 302',
    status: 'ENROLLED',
    enrolledAt: '2025-08-16',
  },
  {
    id: 103,
    studentId: 1,
    sectionId: 4,
    courseCode: 'MATH-201',
    courseTitle: 'Linear Algebra',
    credits: 4,
    instructorName: 'Prof. Elena Rostova',
    scheduleDays: 'Fri',
    scheduleTime: '09:00 AM - 12:00 PM',
    location: 'Euler Hall 401',
    status: 'WAITLISTED',
    enrolledAt: '2025-08-18',
  }
];

export const MOCK_DEGREE_PROGRESS: DegreeProgress = {
  studentId: 1,
  programId: 1,
  programName: 'B.S. in Computer Science',
  totalRequiredCredits: 120,
  creditsCompleted: 48,
  coreCreditsCompleted: 30,
  coreCreditsRequired: 60,
  electiveCreditsCompleted: 18,
  electiveCreditsRequired: 30,
  gpa: 3.82,
  academicStanding: 'EXCELLENT',
  fulfilledCourses: ['CS-101', 'CS-201', 'MATH-101', 'MATH-102', 'ENG-101', 'PHYS-101'],
  remainingCourses: ['CS-301', 'CS-401', 'CS-501', 'MATH-201', 'BUS-402', 'CS-499 Senior Thesis'],
};

export const MOCK_COMPLETED_RECORDS: CompletedCourseRecord[] = [
  {
    id: 1,
    studentId: 1,
    courseId: 10,
    courseCode: 'CS-201',
    courseTitle: 'Object Oriented Programming',
    letterGrade: 'A',
    gradePoints: 4.0,
    semester: 'SPRING',
    year: 2025,
    creditsEarned: 3,
  },
  {
    id: 2,
    studentId: 1,
    courseId: 11,
    courseCode: 'MATH-101',
    courseTitle: 'Calculus I',
    letterGrade: 'A-',
    gradePoints: 3.7,
    semester: 'FALL',
    year: 2024,
    creditsEarned: 4,
  },
  {
    id: 3,
    studentId: 1,
    courseId: 12,
    courseCode: 'PHYS-101',
    courseTitle: 'University Physics I',
    letterGrade: 'B+',
    gradePoints: 3.3,
    semester: 'SPRING',
    year: 2025,
    creditsEarned: 4,
  }
];

export const MOCK_FACULTY_PROFILE: FacultyProfile = {
  id: 1,
  userId: 2,
  facultyIdNumber: 'FAC-8819',
  firstName: 'Alice',
  lastName: 'Smith',
  email: 'prof.smith@nexus.edu',
  department: 'Computer Science & Engineering',
  officeLocation: 'Turing Hall Room 304',
  title: 'Associate Professor',
};

export const MOCK_ROSTER_STUDENTS: ClassRosterStudent[] = [
  {
    enrollmentId: 101,
    studentId: 1,
    studentName: 'John Doe',
    studentIdNumber: 'NEX-2024-8842',
    email: 'john.doe@nexus.edu',
    major: 'Computer Science',
    status: 'ENROLLED',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  },
  {
    enrollmentId: 104,
    studentId: 2,
    studentName: 'Sarah Jenkins',
    studentIdNumber: 'NEX-2024-7711',
    email: 'sarah.j@nexus.edu',
    major: 'Electrical Engineering',
    status: 'ENROLLED',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  },
  {
    enrollmentId: 105,
    studentId: 3,
    studentName: 'Marcus Vance',
    studentIdNumber: 'NEX-2023-9090',
    email: 'marcus.vance@nexus.edu',
    major: 'Mathematics',
    status: 'ENROLLED',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  }
];

export const MOCK_GRADES: GradeRecord[] = [
  {
    id: 1,
    enrollmentId: 101,
    studentId: 1,
    studentName: 'John Doe',
    sectionId: 1,
    courseCode: 'CS-101',
    assignmentTitle: 'Midterm Examination',
    pointsEarned: 94,
    maxPoints: 100,
    letterGrade: 'A',
    comments: 'Excellent logic and efficient algorithm structure.',
    status: 'APPROVED',
    gradedBy: 'prof_smith',
    createdAt: '2025-08-01',
  },
  {
    id: 2,
    enrollmentId: 104,
    studentId: 2,
    studentName: 'Sarah Jenkins',
    sectionId: 1,
    courseCode: 'CS-101',
    assignmentTitle: 'Midterm Examination',
    pointsEarned: 86,
    maxPoints: 100,
    letterGrade: 'B+',
    comments: 'Solid work, review graph search edge cases.',
    status: 'PENDING',
    gradedBy: 'prof_smith',
    createdAt: '2025-08-05',
  },
  {
    id: 3,
    enrollmentId: 105,
    studentId: 3,
    studentName: 'Marcus Vance',
    sectionId: 1,
    courseCode: 'CS-101',
    assignmentTitle: 'Midterm Examination',
    pointsEarned: 78,
    maxPoints: 100,
    letterGrade: 'C+',
    comments: 'Draft grade saved.',
    status: 'DRAFT',
    gradedBy: 'prof_smith',
    createdAt: '2025-08-08',
  }
];

export const MOCK_CHANGE_REQUESTS: ChangeRequest[] = [
  {
    id: 1,
    courseId: 2,
    courseCode: 'CS-301',
    requestType: 'CAPACITY_CHANGE',
    requestedBy: 'prof_smith',
    proposedValue: '50',
    details: 'High student demand for Data Structures fall section. Requesting room expansion to Lovelace 401.',
    status: 'PENDING',
    createdAt: '2025-08-06',
  },
  {
    id: 2,
    courseId: 1,
    courseCode: 'CS-101',
    requestType: 'SCHEDULE_CHANGE',
    requestedBy: 'prof_smith',
    proposedValue: 'Mon, Wed 10:30 AM - 12:00 PM',
    details: 'Adjusting schedule to avoid overlap with CS-501 lab hours.',
    status: 'APPROVED',
    reviewedBy: 3,
    reviewComment: 'Approved - Schedule change verified with registrar.',
    createdAt: '2025-07-28',
  }
];

export const MOCK_PROGRAMS: DegreeProgram[] = [
  {
    id: 1,
    name: 'B.S. in Computer Science',
    code: 'BS-CS',
    department: 'Computer Science & Engineering',
    totalCreditsRequired: 120,
    description: 'Comprehensive software development, algorithms, artificial intelligence, and systems engineering program.',
  },
  {
    id: 2,
    name: 'B.S. in Electrical Engineering',
    code: 'BS-EE',
    department: 'Electrical Engineering',
    totalCreditsRequired: 128,
    description: 'Circuit design, embedded microcontrollers, signal processing, and power systems engineering.',
  },
  {
    id: 3,
    name: 'M.S. in Software Engineering',
    code: 'MS-SE',
    department: 'Computer Science & Engineering',
    totalCreditsRequired: 36,
    description: 'Graduate degree focusing on distributed cloud applications, enterprise architecture, and AI integrations.',
  }
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 1,
    recipientUserId: 1,
    title: 'Enrollment Confirmed',
    message: 'You have been successfully enrolled in CS-101 (Intro to CS).',
    notificationType: 'ENROLLMENT',
    priority: 'HIGH',
    isRead: false,
    createdAt: '10 mins ago',
  },
  {
    id: 2,
    recipientUserId: 1,
    title: 'New Grade Approved',
    message: 'Prof. Smith submitted your grade for Midterm Exam: Grade A (94/100).',
    notificationType: 'GRADE',
    priority: 'MEDIUM',
    isRead: false,
    createdAt: '2 hours ago',
  },
  {
    id: 3,
    recipientUserId: 1,
    title: 'Fall Semester Registration Open',
    message: 'Course registration for Fall 2025 is now active. Check your degree progress audit.',
    notificationType: 'SYSTEM',
    priority: 'LOW',
    isRead: true,
    createdAt: '1 day ago',
  }
];

export const MOCK_ENROLLMENT_TRENDS: EnrollmentTrendItem[] = [
  { month: 'Jan', enrolled: 1200, waitlisted: 150, dropped: 45 },
  { month: 'Feb', enrolled: 1450, waitlisted: 180, dropped: 30 },
  { month: 'Mar', enrolled: 1800, waitlisted: 220, dropped: 60 },
  { month: 'Apr', enrolled: 2100, waitlisted: 310, dropped: 40 },
  { month: 'May', enrolled: 2450, waitlisted: 420, dropped: 55 },
  { month: 'Jun', enrolled: 2900, waitlisted: 380, dropped: 70 },
  { month: 'Jul', enrolled: 3400, waitlisted: 490, dropped: 80 },
];

export const MOCK_DEPARTMENT_DISTRIBUTION: DepartmentDistributionItem[] = [
  { department: 'Computer Science', courses: 24, students: 1280 },
  { department: 'Mathematics', courses: 18, students: 890 },
  { department: 'Electrical Eng.', courses: 15, students: 640 },
  { department: 'Business', courses: 12, students: 510 },
  { department: 'Physics', courses: 10, students: 430 },
];

export const MOCK_COURSE_POPULARITY: CoursePopularityItem[] = [
  { courseCode: 'CS-101', title: 'Intro to Programming', enrolled: 45, capacity: 45, waitlist: 12 },
  { courseCode: 'CS-301', title: 'Data Structures', enrolled: 35, capacity: 35, waitlist: 8 },
  { courseCode: 'MATH-201', title: 'Linear Algebra', enrolled: 38, capacity: 40, waitlist: 3 },
  { courseCode: 'CS-501', title: 'Software Architecture', enrolled: 22, capacity: 30, waitlist: 0 },
  { courseCode: 'BUS-402', title: 'Corporate Strategy', enrolled: 28, capacity: 30, waitlist: 2 },
];

export const MOCK_FACULTY_WORKLOAD: FacultyWorkloadItem[] = [
  { facultyName: 'Prof. Alice Smith', department: 'Computer Science', sectionsCount: 3, totalStudents: 99, teachingHours: 12 },
  { facultyName: 'Prof. Robert Taylor', department: 'Computer Science', sectionsCount: 2, totalStudents: 52, teachingHours: 8 },
  { facultyName: 'Prof. Elena Rostova', department: 'Mathematics', sectionsCount: 4, totalStudents: 140, teachingHours: 16 },
  { facultyName: 'Prof. David Miller', department: 'Electrical Eng.', sectionsCount: 2, totalStudents: 48, teachingHours: 9 },
];
